version: 2
updates:
  # Maintain dependencies for our yarn packages.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
